using System.Numerics;
using System.Text;
using System.Text.Json;
using CarpaNet.Identity;
using Org.BouncyCastle.Crypto.EC;
using TangentSpace.Identity;
using Xunit;

namespace TangentSpace.Tests;

/// <summary>DID signing-key decoding and compact signature verification, against vectors generated by
/// the official atproto key implementations and a real PLC document.</summary>
public sealed class DidSigningKeyTests
{
    private const string Author = "did:example:author";

    [Theory, InlineData(0), InlineData(1)]
    public void A_multikey_verifies_its_official_compact_signature_and_rejects_tampering(int number)
    {
        using var parsed = JsonDocument.Parse(Vectors);
        var vector = parsed.RootElement[number];
        var key = Key(vector.GetProperty("multikey").GetString()!);
        Assert.Equal(vector.GetProperty("curve").GetString(), key.Curve);
        Assert.Equal(key.Curve == "P-256" ? "ES256" : "ES256K", key.JwtAlgorithm);
        var input = Encoding.UTF8.GetBytes(vector.GetProperty("signingInput").GetString()!);
        var signature = Convert.FromHexString(vector.GetProperty("signatureHex").GetString()!);
        Assert.True(key.VerifySignature(input, signature));
        Assert.False(key.VerifySignature(Encoding.UTF8.GetBytes("changed context"), signature));
        Assert.False(key.VerifySignature(input, signature[..63]));
        var altered = (byte[])signature.Clone(); altered[0] ^= 1;
        Assert.False(key.VerifySignature(input, altered));
        var order = CustomNamedCurves.GetByName(key.Curve == "P-256" ? "secp256r1" : "secp256k1").N.ToByteArrayUnsigned();
        var highS = new BigInteger(order, true, true) - new BigInteger(signature.AsSpan(32), true, true);
        var highBytes = highS.ToByteArray(true, true);
        altered = (byte[])signature.Clone(); Array.Clear(altered, 32, 32); highBytes.CopyTo(altered, 64 - highBytes.Length);
        Assert.False(key.VerifySignature(input, altered));
    }

    [Theory]
    [InlineData("other-document")][InlineData("other-controller")][InlineData("other-key-id")]
    [InlineData("missing-key")][InlineData("duplicate-key")][InlineData("mismatched-key-type")]
    [InlineData("wrong-base")][InlineData("invalid-base58")][InlineData("leading-zero")][InlineData("too-long")]
    public void Hostile_or_ambiguous_DID_keys_are_rejected(string change)
    {
        using var parsed = JsonDocument.Parse(Vectors);
        var document = Document(parsed.RootElement[0].GetProperty("multikey").GetString()!);
        var key = document.VerificationMethod[0];
        switch (change)
        {
            case "other-document": document.Id = "did:example:other"; break;
            case "other-controller": key.Controller = "did:example:other"; break;
            case "other-key-id": key.Id = "did:example:other#atproto"; break;
            case "missing-key": document.VerificationMethod.Clear(); break;
            case "duplicate-key": document.VerificationMethod.Add(new VerificationMethod { Id = "#atproto", Controller = Author, Type = key.Type, PublicKeyMultibase = key.PublicKeyMultibase }); break;
            case "mismatched-key-type": key.Type = "EcdsaSecp256k1VerificationKey2019"; break;
            case "wrong-base": key.PublicKeyMultibase = "m" + key.PublicKeyMultibase![1..]; break;
            case "invalid-base58": key.PublicKeyMultibase = "z0" + key.PublicKeyMultibase![2..]; break;
            case "leading-zero": key.PublicKeyMultibase = "z1" + key.PublicKeyMultibase![1..]; break;
            case "too-long": key.PublicKeyMultibase = "z" + new string('2', 128); break;
        }
        Assert.Throws<InvalidDataException>(() => DidSigningKey.FromDidDocument(document, Author));
    }

    [Fact]
    public void A_relative_atproto_key_id_is_controlled_by_the_document()
    {
        using var parsed = JsonDocument.Parse(Vectors);
        var document = Document(parsed.RootElement[0].GetProperty("multikey").GetString()!);
        document.VerificationMethod[0].Id = "#atproto";
        Assert.Equal(Author, DidSigningKey.FromDidDocument(document, Author).Did);
    }

    [Fact]
    public void A_PLC_document_with_a_2019_key_type_verifies_a_real_service_signature()
    {
        using var fixture = JsonDocument.Parse(PlcFixture);
        var authority = DidDocument.FromJson(fixture.RootElement.GetProperty("document").GetRawText());
        var key = DidSigningKey.FromDidDocument(authority, authority.Id);
        var signature = fixture.RootElement.GetProperty("expiredServiceSignature");
        Assert.True(key.VerifySignature(Encoding.ASCII.GetBytes(signature.GetProperty("signingInput").GetString()!),
            Convert.FromHexString(signature.GetProperty("signatureHex").GetString()!)));
    }

    private static DidSigningKey Key(string multikey) => DidSigningKey.FromDidDocument(Document(multikey), Author);

    private static DidDocument Document(string multikey) => new()
    {
        Id = Author,
        VerificationMethod = [new VerificationMethod { Id = Author + "#atproto", Controller = Author, Type = "Multikey", PublicKeyMultibase = multikey }]
    };

    // A public PLC document and an expired service signature captured from a real PDS. This tests
    // key and signature decoding only; an expired JWT is not valid service authorization.
    private const string PlcFixture = """
{"document":{"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/secp256k1-2019/v1"],"id":"did:plc:yblwluenzocgiqpmu4ip7six","alsoKnownAs":["at://tangent-authority.test"],"verificationMethod":[{"id":"#atproto","type":"EcdsaSecp256k1VerificationKey2019","controller":"did:plc:yblwluenzocgiqpmu4ip7six","publicKeyMultibase":"zNG8hhDBG9gTy1aMrHBVXQNoVWodeW8w56jfXt9GvmutDGB2LkskwtYpRhd5jE2KrLQnZJJePqY8cK1ncCi5cRkLQ"}],"service":[{"id":"#atproto_pds","type":"AtprotoPersonalDataServer","serviceEndpoint":"http://localhost:2583"}]},"expiredServiceSignature":{"expiresAt":1788988298,"signingInput":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJpYXQiOjE3ODg5ODgyOTUsImlzcyI6ImRpZDpwbGM6eWJsd2x1ZW56b2NnaXFwbXU0aXA3c2l4IiwiYXVkIjoiZGlkOnBsYzpzYTJmbDJ0MjduN202NHBibDR4YXpkc20jdGFuZ2VudCIsImV4cCI6MTc4ODk4ODI5OCwibHhtIjoiY29tLmF0cHJvdG8uc2ltcGxlc3BhY2UuY2hlY2tVc2VyQWNjZXNzIiwianRpIjoiODBmMDFkOWIzYWFjMzJhYjFmNjg0ZmZjMDEwN2ZlNWEifQ","signatureHex":"752c6c4b067c1639d204a7e9f4af83f2819fbd3d1c3b59c4642b2ef39759d6ce02e50c015ba25073ccf445015587cee4322d2cf30c925abd7f7eb4481dec2624"}}
""";

    // Public vectors generated by the pinned official serializer and keypair implementations.
    private const string Vectors = """
[{"curve":"secp256k1","multikey":"zQ3shuCPf2Fkw8aWDT41Tbq4mXi73WcpkEsgjZCpbWUgtG3kh","signingInput":"eyJhbGciOiJ0ZXN0In0.eyJpc3MiOiJkaWQ6ZXhhbXBsZTphdXRob3IifQ","signatureHex":"3ca74af623d46ac2cf80d0dfcea13e64b91db4c67ec2fb1ba01e9422caa5fe06516d5a285700616f76bea1d1ced98b508ec505f5ef177c2176d2e3c7b9308190"},{"curve":"P-256","multikey":"zDnaejR8NosRdn9e77oK5LSu1akYxRgNA9aS6bNvsziVWownc","signingInput":"eyJhbGciOiJ0ZXN0In0.eyJpc3MiOiJkaWQ6ZXhhbXBsZTphdXRob3IifQ","signatureHex":"bf1bb04425f5396aadf618fe6ae414a66a0368e8a1cc9978c0ebde5348e47c1630e5a5045436e968b8843411562a03d958c3be22acc8c72f7bd0b3cfe04e5304"}]
""";
}
