<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sylin.Koan.App" Version="[1.0.38]" />
    <PackageReference Include="Sylin.Koan.Data.Connector.Sqlite" Version="[1.0.46]" />
  </ItemGroup>

</Project>
